language: c

install:
      - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
      - xbuild OmniSharp.sln /p:Configuration=Debug /p:Platform="Any CPU"
      - nunit-console ./OmniSharp.Tests/bin/Debug/OmniSharp.Tests.dll
