language: c

install:
      - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
      - xbuild
      - /usr/bin/cli --runtime=v4.0 /usr/lib/nunit/nunit-console.exe ./OmniSharp.Tests/bin/Debug/OmniSharp.Tests.dll
